feat: The first major release for vpc endpoints
boldlink/terraform-aws-vpc-endpoints pull request #2
Opened 2023-08-10 21:07 UTC by patrickmukumbu

# Description

This PR was created for the first major release with the ability to create multiple endpoints of different types

## Features/Fixes/Patches/Changes list:

Please check the [CHANGELOG.md](https://github.com/boldlink/terraform-aws-vpc-endpoints/blob/release/release-1.0.0
/CHANGELOG.md#100---2023-08-10)

## Checklists:

### PR Owners Checklist:
* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ ] Have you checked there aren't open [Pull Requests](../../../pulls) of upstream or parallel code that will cause conflicts?
* [ ] Have you updated the `CHANGELOG.md`?
* [ ] Have you updated the `README.md`(s)?
* [ ] OWNER: Does your submission pass?
    * [ ] Pre-commit (attach logs/print screen to this PR)
    * [ ] Checkov/terrascan (attach logs/print screen to this PR)
    * [ ] Terraform resources examples build/destroy successfully with Terraform 0.14.11 minimum?
* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?
* [ ] First PR? Have you deleted `## How to use this template...` from the root `.README.md`?

### PR Reviewers Checklists?
* [ ] Are all your comments/changes resolved?
* [ ] Are you happy with the OWNER checklists and additional information provided?
* [ ] Does your review tests pass?
    * [ ] Terraform resources examples build/destroy successfully with Terraform 0.14.11 minimum?

2023-08-22 15:11 UTC, hugoalmeida264 requested changes

2023-08-22 15:11 UTC, hugoalmeida264 commented on examples/complete/main.tf
> +      service_name        = "com.amazonaws.${local.region}.ssm"
`com.amazonaws` can be replaced by a data source from locals, this is because on china this dns suffix is different ;)

2023-08-22 15:11 UTC, hugoalmeida264 commented on README.md
> +- **Rapid Deployment:** Harness the power of efficient automation – deploying your endpoints becomes a swift, hassle-free task.
I see what you are trying to say here:
`- **Rapid Deployment:** Harness the power of efficient automation – deploying your endpoints becomes a swift, hassle-free task.`
And it comes a bit "marketingsy" from my perspective since automation comes from a different work of automation...

2023-08-22 15:11 UTC, hugoalmeida264 commented on README.md
> +- **Dynamic Endpoint Scalability:** The module's capacity to seamlessly generate multiple endpoints dynamically grants unparalleled flexibility and adaptability to evolving operational needs.
Same here, are you using chatgpt?

2023-08-22 15:11 UTC, hugoalmeida264 commented on README.md
> +  source             = "./../../"
On README.md use the official source
```
...
source = "boldlink/aws/vpc-endpoints"
version = "<latest_version>"
...
```

2023-08-23 06:43 UTC, patrickmukumbu commented on README.md
> +- **Rapid Deployment:** Harness the power of efficient automation – deploying your endpoints becomes a swift, hassle-free task.
I have reverted to simplified description

2023-08-23 06:44 UTC, patrickmukumbu commented on README.md
> +- **Dynamic Endpoint Scalability:** The module's capacity to seamlessly generate multiple endpoints dynamically grants unparalleled flexibility and adaptability to evolving operational needs.
Yes I used chatgpt where I told it to make what I had sound more professional

2023-08-23 06:54 UTC, patrickmukumbu commented on examples/complete/main.tf
> +      service_name        = "com.amazonaws.${local.region}.ssm"
Done

2023-08-23 06:54 UTC, patrickmukumbu commented on README.md
> +  source             = "./../../"
Added

2023-08-23 14:35 UTC, hugoalmeida264 requested changes

2023-08-23 14:35 UTC, hugoalmeida264 commented on README.md
> +  version            = 1.0.0
Dont hardcode the version, instead put:
`version = <latest_version_nr>`

2023-08-23 14:35 UTC, hugoalmeida264 commented on examples/complete/data.tf
> +data "aws_partition" "current" {}
New line missing

2023-08-23 14:35 UTC, hugoalmeida264 commented on examples/minimum/data.tf
> +data "aws_partition" "current" {}
new line spacing

2023-08-23 14:35 UTC, hugoalmeida264 commented on tests/supportingResources/README.md
> +* VPC with public and Private subnets
`* VPC with internal only subnets with no internet access.`

2023-08-25 10:11 UTC, hugoalmeida264 approved these changes

2023-08-25 10:12 UTC, merged